# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0002_auto_20170501_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='knighthood',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='earth.Knighthood', verbose_name='\u041e\u0440\u0434\u0435\u043d'),
        ),
    ]
