# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0003_auto_20170502_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earth.Test', verbose_name='\u0422\u0435\u0441\u0442'),
        ),
    ]
